### ISSUE TITLE
RPP性能只有43.9

### ISSUE THREAD

**Issue by luuuyi** [syfafterzy/PCB_RPP#4]
你好，感谢你将代码分享出来。
我在跑你的实验时发现，光是训PCB，按照你的配置是可以得到给出来的性能的，但是训练RPP的时候在market1501上只有43.9的mAP，我想确定下是第一步只训练PCB20个epoch，并且学习率不下降？（因为下降次数为20epoch）；第二步训练RPP50个epoch，然后20次的时候下降一次学习率。这种默认的配置是正确的么

**Comment by luuuyi** [comment]
打扰了，应该是服务器执行sh的时候出问题了

**Comment by huo123lijuan** [comment]
你好，你的性能达论文中的了吗，参数是怎么样的设置
